### ISSUE TITLE
User_id, Row vs Column

### ISSUE THREAD

**Issue by ghost** [klaravel/settings#1]
Hi,
First off thanks for the easy to use package. 
I am new to implementing settings so please forgive me if this is an amateur question.

I am curious to know should the settings migration reference the ID on the users table? Currently the default package lists an ID for each key, but different users will have different requirements. How can each unique user be catered for in the default environment?

Secondly, I am curious to know what is the advantage of having the values appear as Keys and Values in each row, as opposed to having columns that can be filled in for each user? It seems like with this package the Keys will be multiplied for each user, whereby if each Key was a column it would only have to be entered once- assuming a constant settings methodology for the entire App. I guess this package is more suitable to a dynamic settings implementation?

Hope this makes sense,
Cheers

**Comment by klaravel** [comment]
@Mapamatician  

Currently this package don't support but Let me check if it's possible then I will add that feature.
